### ISSUE TITLE
无法链接开发文档-抱歉！源站出现问题，暂时无法访问！

### ISSUE THREAD

**Issue by Chenjinyi** [shiyunjin/SWAPIDC-Suggest#1]
**描述错误**

Swap云中心

抱歉！源站出现问题，暂时无法访问！

**重现**

重现行为的步骤：
1.登陆云中心
2.点击“开发者中心”
3.向下滚动到'开发文档'
4.出现 抱歉！源站出现问题，暂时无法访问！

**预期行为**

让我不知道怎么快乐的写BUG

**Comment by shiyunjin** [comment]
开发文档目前并没有整理公开,请参考样例插件和默认模版进行开发,V5版改动较大如果开发的是模版类可以等几天

**Comment by Chenjinyi** [comment]
也就是说V5对开发插件影响不大？

**Comment by shiyunjin** [comment]
只要使用官方内置接口影响就不大,比如说原来的插件取uid有很多插件直接去取session值导致v5不兼容,需要使用标准的User::Uid()取当前用户uid

**Comment by Chenjinyi** [comment]
OK。
如果遇到开发上的问题可以向你发送邮件吗？

**Comment by shiyunjin** [comment]
开发问题建议进群问,不建议在这里发,这里是收集功能请求和问题反馈的
