### ISSUE TITLE
SWAP IDC v5 邮件设置 

### ISSUE THREAD

**Issue by ccdalao** [shiyunjin/SWAPIDC-Suggest#2]
**描述错误**

SWAP IDC v5 邮件设置  发送测试邮件
发生后无法正常收到邮件（配置复制旧版本的内容绝对一样(仔细核对过了)） 看截图区 图2,3对比
而且点击提交后上方的淡蓝色提示框无文字显示 看截图区 图片1

**重现**

重现行为的步骤：
1.去后台
2.点击设置->邮件设置->通过SMTP服务器发送邮件
3.配置完成通过SMTP服务器发送邮件后->测试邮件发送后收不到邮件并且上方提示框无文字显示

**预期行为**

希望成功发送邮件

**截图**

图片1：http://yunun.cc/index/img/1.png
图2,3 http://yunun.cc/index/img/2.png http://yunun.cc/index/img/3.png

**桌面（请填写以下信息）：**
  - 操作系统  Linux
  - 浏览器   chrome
  - 版本     0.5.0.3

**附加背景**

我是CCDALAO

**Comment by shiyunjin** [comment]
试一下 0.5.0.4版本

**Comment by ccdalao** [comment]
> 试一下0.5.0.4版本
OK,正常了
